export const CODE = 'CODE';
export const GET_COMPANYID = 'GET_COMPANYID';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_COMPANY_SELLER = 'GET_COMPANY_SELLER';
export const GET_EXISTING_SERVICES = 'GET_EXISTING_SERVICES';
export const GET_DEFAULT_CONTRACT = 'GET_DEFAULT_CONTRACT';